In [1]:
import pandas as pd
import numpy as np
import copy
df_orig = pd.read_excel("ventas.xls")
df_working = copy.deepcopy(df_orig)

FileNotFoundError: [Errno 2] No such file or directory: 'ventas.xls'

In [126]:
df_orig.iloc[:50,:]

,Unnamed: 0,Total,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,NaN,Cadereyta,NaN,Coahuila,NaN,Durango,NaN,Expos F,NaN,Laredo,...,Online,NaN,Queretaro,NaN,Reynosa,NaN,San Luis,NaN,NaN,NaN
1,NaN,Total libre de impuestos,Ctdad Ordenada,Total libre de impuestos,Ctdad Ordenada,Total libre de impuestos,Ctdad Ordenada,Total libre de impuestos,Ctdad Ordenada,Total libre de impuestos,...,Total libre de impuestos,Ctdad Ordenada,Total libre de impuestos,Ctdad Ordenada,Total libre de impuestos,Ctdad Ordenada,Total libre de impuestos,Ctdad Ordenada,Total libre de impuestos,Ctdad Ordenada
2,Total,2425243.975,616,25556364.19,3923.5,789616.52,136.5,1425365.69,192.5,9963312.24,...,5400646.44,721,25689779.78,4305,5635591.85,731.5,16341428.88,2212,186262124.93,28220.5
3,01 abr 2022,NaN,NaN,293340.355,52.5,33364.555,7,NaN,NaN,89964.49,...,8358.945,3.5,200484.13,31.5,52678.465,7,427864.815,42,1542057.37,248.5
4,Producto 1,NaN,NaN,15389.535,3.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15389.535,3.5
5,Producto 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35295.68,7
6,Producto 3,NaN,NaN,37488.08,7,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,18528.895,3.5,NaN,NaN,18528.895,3.5,200206.51,38.5
7,Producto 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25080.09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25080.09,3.5
8,Producto 5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28057.33,3.5
9,Producto 6,NaN,NaN,28754.95,3.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28754.95,3.5
10,Producto 7,NaN,NaN,20082.755,3.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,23628.08,3.5,43710.835,7
11,Producto 8,NaN,NaN,26609.065,3.5,26609.065,3.5,NaN,NaN,28580.09,...,NaN,NaN,26765.375,3.5,NaN,NaN,NaN,NaN,108563.595,14
12,Producto 9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29460.34,...,NaN,NaN,29460.34,3.5,NaN,NaN,NaN,NaN,58920.68,7
13,Producto 10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,41338.885,3.5,83772.64,7,198642.71,17.5
14,Producto 11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,26087.74,7,NaN,NaN,NaN,NaN,37922.22,10.5
15,Producto 12,NaN,NaN,58672.32,17.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58672.32,17.5
16,Producto 13,NaN,NaN,18798.885,3.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18798.885,3.5
17,Producto 14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,19754.245,3.5,NaN,NaN,NaN,NaN,19754.245,3.5
18,Producto 15,NaN,NaN,39223.625,3.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,38875.795,3.5,78099.42,7
19,Producto 16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22154.825,3.5
20,Producto 17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38331.825,3.5
21,Producto 18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,25903.185,3.5,25903.185,3.5
22,Producto 19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,46751.67,3.5,NaN,NaN,NaN,NaN,46751.67,3.5
23,Producto 20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,50677.62,3.5,50677.62,3.5
24,Producto 21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6843.97,...,NaN,NaN,7963.69,3.5,NaN,NaN,NaN,NaN,14807.66,7
25,NaN,NaN,NaN,NaN,NaN,6755.49,3.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51598.575,28
26,NaN,NaN,NaN,9239.23,3.5,NaN,NaN,NaN,NaN,NaN,...,8358.945,3.5,NaN,NaN,11339.58,3.5,23144.205,10.5,69680.45,28
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14720.58,3.5
28,Producto 22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,25172.175,3.5,NaN,NaN,NaN,NaN,49145.67,7
29,Producto 23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,163334.395,7,163334.395,7
30,Producto 24,NaN,NaN,39081.91,3.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39081.91,3.5
31,02 abr 2022,37086.7,7,269843.945,56,NaN,NaN,NaN,NaN,173892.53,...,NaN,NaN,382963.385,49,54760.475,14,273894.425,52.5,2336219.48,406
32,Producto 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10316.39,3.5
33,Producto 25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,23142.98,3.5,NaN,NaN,NaN,NaN,23142.98,3.5
34,Producto 3,NaN,NaN,21800.31,3.5,NaN,NaN,NaN,NaN,20019.965,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83344.695,14
35,Producto 5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26720.855,3.5
36,Producto 6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81848.55,10.5
37,Producto 26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46710.37,3.5
38,Producto 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,40404,7,104649.895,17.5
39,Producto 8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,26765.375,3.5,NaN,NaN,NaN,NaN,82069.995,10.5
40,Producto 9,NaN,NaN,97862.87,10.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,29631.665,3.5,155715.175,17.5
41,Producto 10,NaN,NaN,45284.715,3.5,NaN,NaN,NaN,NaN,41586.475,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125686.68,10.5
42,Producto 11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29167.565,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40331.2,10.5
43,Producto 12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14595.98,...,NaN,NaN,14534.065,3.5,12819.905,3.5,NaN,NaN,65619.75,17.5
44,Producto 13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38843.7,7
45,Producto 27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,13380.325,3.5,NaN,NaN,NaN,NaN,13380.325,3.5
46,Producto 28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29174.04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53452.49,7
47,Producto 29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,30119.775,3.5,NaN,NaN,61356.26,7
48,Producto 30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,38236.73,7,NaN,NaN,NaN,NaN,53932.13,10.5
49,Producto 16,15236.935,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,23507.435,3.5,NaN,NaN,27207.67,3.5,107035.635,17.5

In [98]:
dates = []
indeces = []
for i, obj in enumerate(df_orig["Unnamed: 0"]):
    if type(obj) is str:
        if len(obj) > 15:
            dates.append(obj)
            indeces.append(i)
            
print(dates)
print(indeces)

['     01 abr 2022', '     02 abr 2022', '     03 abr 2022', '     04 abr 2022', '     05 abr 2022', '     06 abr 2022', '     07 abr 2022', '     08 abr 2022', '     09 abr 2022', '     10 abr 2022', '     11 abr 2022', '     12 abr 2022', '     13 abr 2022', '     14 abr 2022', '     15 abr 2022', '     16 abr 2022', '     17 abr 2022', '     18 abr 2022', '     19 abr 2022', '     20 abr 2022', '     21 abr 2022', '     22 abr 2022', '     23 abr 2022', '     24 abr 2022', '     25 abr 2022', '     26 abr 2022', '     27 abr 2022', '     28 abr 2022', '     29 abr 2022', '     30 abr 2022', '     01 may 2022', '     02 may 2022', '     03 may 2022', '     04 may 2022', '     05 may 2022', '     06 may 2022', '     07 may 2022', '     08 may 2022', '     09 may 2022', '     10 may 2022', '     11 may 2022', '     12 may 2022', '     13 may 2022', '     14 may 2022', '     15 may 2022', '     16 may 2022', '     17 may 2022', '     18 may 2022', '     19 may 2022', '     20 may 2022', '     21 may 2022', '     22 may 2022', '     23 may 2022', '     24 may 2022', '     25 may 2022', '     26 may 2022', '     27 may 2022', '     28 may 2022', '     29 may 2022', '     30 may 2022', '     31 may 2022', '     01 jun 2022', '     02 jun 2022', '     03 jun 2022', '     04 jun 2022', '     05 jun 2022', '     06 jun 2022', '     07 jun 2022', '     08 jun 2022', '     09 jun 2022', '     10 jun 2022', '     11 jun 2022', '     12 jun 2022', '     13 jun 2022', '     14 jun 2022', '     15 jun 2022', '     16 jun 2022', '     17 jun 2022', '     18 jun 2022', '     19 jun 2022', '     20 jun 2022', '     21 jun 2022', '     22 jun 2022', '     23 jun 2022', '     24 jun 2022', '     25 jun 2022', '     26 jun 2022', '     27 jun 2022', '     28 jun 2022', '     29 jun 2022', '     30 jun 2022']
[3, 31, 72, 114, 153, 191, 220, 256, 291, 333, 376, 416, 446, 484, 523, 525, 565, 597, 633, 672, 712, 740, 774, 813, 845, 882, 908, 946, 979, 1006, 1053, 1099, 1132, 1160, 1199, 1228, 1260, 1306, 1352, 1397, 1446, 1480, 1522, 1562, 1605, 1649, 1694, 1730, 1766, 1809, 1855, 1906, 1945, 1998, 2045, 2088, 2138, 2180, 2239, 2289, 2348, 2418, 2447, 2492, 2533, 2579, 2616, 2662, 2695, 2727, 2758, 2797, 2847, 2891, 2941, 2980, 3016, 3050, 3081, 3129, 3171, 3215, 3251, 3286, 3329, 3359, 3406, 3452, 3499, 3542, 3581]

In [121]:
dates_col = np.zeros_like(df_orig["Unnamed: 0"])
dates_col[:indeces[0]] = np.nan

for i in range(1, len(indeces)):
    dates_col[indeces[i-1]:indeces[i]] = dates[i-1]
    
dates_col[indeces[-1]:] = dates[-1]

In [122]:
df_working["Dates"] = dates_col

In [125]:
df_working[["Dates","Unnamed: 0"]].iloc[70:,:]

                 Dates        Unnamed: 0
70         02 abr 2022       Producto 23
71         02 abr 2022       Producto 44
72         03 abr 2022       03 abr 2022
73         03 abr 2022        Producto 1
74         03 abr 2022       Producto 45
...                ...               ...
3613       30 jun 2022       Producto 42
3614       30 jun 2022       Producto 23
3615       30 jun 2022       Producto 58
3616       30 jun 2022      Producto 104
3617       30 jun 2022       Producto 60

[3548 rows x 2 columns]