In [22]:
from datetime import timedelta
import pandas as pd
import numpy as np

df = pd.read_csv('C:/Users/ricar/Desktop/GitHub/colchoncitos/WorkingDB.csv')

In [23]:
df['Total'] = df['Cadereyta Cantidad ordenada']+df['Coahuila Cantidad ordenada']+df['Durango Cantidad ordenada']+df['Expos F Cantidad ordenada']+df['Laredo Cantidad ordenada']+df['Monterrey Cantidad ordenada']+df['Online Cantidad ordenada']+df['Queretaro Cantidad ordenada']+df['Reynosa Cantidad ordenada']+df['San Luis Cantidad ordenada']
df['Fecha'] = pd.to_datetime(df.Fecha, format = '%Y-%m-%d')

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3078 entries, 0 to 3077
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Producto                     3078 non-null   object
 1   Cadereyta Precio por unidad  3078 non-null   float64
 2   Cadereyta Cantidad ordenada  3078 non-null   float64
 3   Coahuila Precio por unidad   3078 non-null   float64
 4   Coahuila Cantidad ordenada   3078 non-null   float64
 5   Durango Precio por unidad    3078 non-null   float64
 6   Durango Cantidad ordenada    3078 non-null   float64
 7   Expos F Precio por unidad    3078 non-null   float64
 8   Expos F Cantidad ordenada    3078 non-null   float64
 9   Laredo Precio por unidad     3078 non-null   float64
 10  Laredo Cantidad ordenada     3078 non-null   float64
 11  Monterrey Precio por unidad  3078 non-null   float64
 12  Monterrey Cantidad ordenada  3078 non-null   float64
 13  Online Precio por unidad     3078 non-null   float64
 14  Online Cantidad ordenada     3078 non-null   float64
 15  Queretaro Precio por unidad  3078 non-null   float64
 16  Queretaro Cantidad ordenada  3078 non-null   float64
 17  Reynosa Precio por unidad    3078 non-null   float64
 18  Reynosa Cantidad ordenada    3078 non-null   float64
 19  San Luis Precio por unidad   3078 non-null   float64
 20  San Luis Cantidad ordenada   3078 non-null   float64
 21  Fecha                        3078 non-null   datetime64[ns]
 22  Total                        3078 non-null   float64
dtypes: datetime64[ns](1), float64(21), object(1)
memory usage: 553.2+ KB

In [25]:
fecha_inicio = df[df['Producto'] =='Producto 1'].iloc[0,21]
fecha_inicio
fecha_fin = fecha_inicio + timedelta(days = 91)

In [26]:
def add_days(df_prod, df_gen, fecha_inicio, fecha_fin, producto):
    fecha = fecha_inicio
    while fecha != fecha_fin:
        if(len(df_prod[df_prod['Fecha'] == fecha]) == 0):
            entrada = pd.Series([producto,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,fecha,0], index = df_gen.columns)
            df_gen = pd.concat([df_gen,entrada.to_frame().T], ignore_index = True)
        fecha = fecha + timedelta(days = 1)
    return df_gen

In [27]:
df_copy_gen = df.copy()
df_copy_prod = df[df['Producto'] =='Producto 1']
df2 = add_days(df_copy_prod, df_copy_gen, fecha_inicio, fecha_fin, 'Producto 1')
df2_proucto1 = df2[df2['Producto'] =='Producto 1'].sort_values('Fecha').sort_values('Fecha')

In [28]:
def get_day(str):
    str1 = str[5:7]
    str2 = str[8:10]
    str = str1 + '.' + str2
    return str

In [29]:
df2_proucto1['Fecha'] = df2_proucto1['Fecha'].astype(str)
df2_proucto1['Fecha'] = df2_proucto1['Fecha'].apply(get_day)
df2_proucto1

,Producto,Cadereyta Precio por unidad,Cadereyta Cantidad ordenada,Coahuila Precio por unidad,Coahuila Cantidad ordenada,Durango Precio por unidad,Durango Cantidad ordenada,Expos F Precio por unidad,Expos F Cantidad ordenada,Laredo Precio por unidad,...,Online Precio por unidad,Online Cantidad ordenada,Queretaro Precio por unidad,Queretaro Cantidad ordenada,Reynosa Precio por unidad,Reynosa Cantidad ordenada,San Luis Precio por unidad,San Luis Cantidad ordenada,Fecha,Total
0,Producto 1,0.0,0.0,4397.01,3.5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,04.01,3.5
24,Producto 1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,04.02,3.5
61,Producto 1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,04.03,3.5
3078,Producto 1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,04.04,0
3079,Producto 1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,04.05,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3118,Producto 1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,06.26,0
3119,Producto 1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,06.27,0
2979,Producto 1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,06.28,3.5
3120,Producto 1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,06.29,0
3121,Producto 1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,06.30,0

In [32]:
df2_proucto1['Fecha'] = df2_proucto1['Fecha'].astype(float)
df2_proucto1['Total'] = df2_proucto1['Total'].astype(float)

In [34]:

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import statsmodels.api as sm
X = df2_proucto1['Fecha']
y = df2_proucto1['Total']
X = sm.add_constant(X)
X_train, X_test = X.iloc[:-20], X.iloc[-20:]
y_train, y_test = y.iloc[:-20], y.iloc[-20:]
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error (MSE):", mse)
ols_model = sm.OLS(y_train, X_train).fit()
print(ols_model.summary())

Mean Squared Error (MSE): 17.0462573601194
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.014
Method:                 Least Squares   F-statistic:                   0.02423
Date:                Wed, 06 Mar 2024   Prob (F-statistic):              0.877
Time:                        18:01:17   Log-Likelihood:                -220.15
No. Observations:                  71   AIC:                             444.3
Df Residuals:                      69   BIC:                             448.8
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          3.9284      4.697      0.836      0.406      -5.441      13.298
Fecha         -0.1490      0.957     -0.156      0.877      -2.058       1.760
==============================================================================
Omnibus:                       83.734   Durbin-Watson:                   2.067
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              927.259
Skew:                           3.549   Prob(JB):                    4.45e-202
Kurtosis:                      19.219   Cond. No.                         37.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.